services:
  db:
    image: postgres:16
    container_name: whltv-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  dataaccessapi:
    build:
      context: ./DataAccessAPI
      dockerfile: Dockerfile
    container_name: whltv-dataaccessapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
  demopipelineworker:
    build:
      context: ..
      dockerfile: WHLTV/WHLTV.Pipeline/src/WHLTV.DemoPipeline.Worker/Dockerfile
    container_name: whltv-demo-pipeline-worker
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Production
      - Storage__ImportRoot=${STORAGE_IMPORT_ROOT}
      - Storage__WorkRoot=${STORAGE_WORK_ROOT}
      - Storage__ParquetRoot=${STORAGE_PARQUET_ROOT}
    volumes:
      - ${HOST_IMPORT_PATH}:${STORAGE_IMPORT_ROOT}
      - ${HOST_WORK_PATH}:${STORAGE_WORK_ROOT}
      - ${HOST_PARQUET_PATH}:${STORAGE_PARQUET_ROOT}
    depends_on:
      - db
  frontend:
    build:
      context: ./Frontend
      dockerfile: dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  pgdata:
